index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: index/index.html.twig
deconnexion:
    path: /deconnexion

